### ISSUE TITLE
Troubleshooting trin startup issue after discv5 version bump

### ISSUE THREAD

**Issue by njgheorghita** [carver/trin#37]
I'm having trouble getting trin up and consistently running after rebasing my various branches to the latest commit. It seems to be the port to the new discv5 `0.1.0-beta.5` version. But, essentially my trin client isn't starting. Never experienced this kind of issue with trin before. I've rolled back to the pre discv5 version bump, and things appear to be working correctly. Is this an issue anybody else is experiencing? @SamWilsn @carver ? Maybe there's some new configuration required that I'm missing? My best, but most likely inadequate, debugging attempts haven't revealed much insight into what's going wrong, but it seems like the cause might be somewhere within the `discv5` library. 

```
Jul 01 16:35:07.940  INFO trin: About to spawn portal p2p with boot nodes: []
Jul 01 16:35:17.943 DEBUG trin::portalnet::socket: STUN claims that public network endpoint is: Err("Timed out waiting for STUN server reply")
Jul 01 16:35:17.951  INFO trin::portalnet::discovery: Starting discv5 with local enr encoded=enr:-IS4QKXQytRMuNJcJiING0ORNuGWhBgtS0Y2qSeydxUIqI88PCQ_k6txUKsPHKcTGEPI7Sqas37q9z-nEsM76-2CNoYBgmlkgnY0gmlwhMCoAWSJc2VjcDI1NmsxoQKMMoaHJ0mz-Jv1uCJpRHV5rFNoAxwtAwVMTJJ_EsLrcoN1ZHCCIyg decoded=ENR: NodeId: 0xf3d0..abcf, Socket: Some(192.168.1.100:9000)
Jul 01 16:35:17.954 DEBUG discv5::discv5: Service is already shutdown
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: "ServiceNotStarted"', src/main.rs:53:80
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by SamWilsn** [comment]
I probably missed something dumb when I ported to discv5, let me take a look.
