### ISSUE TITLE
Track State Network peers independently from discv5 base layer

### ISSUE THREAD

**Issue by carver** [carver/trin#46]
As I imagine it, that means: replicating (reusing?) the Kademlia bucket code used in the discv5 crate, but with state-net clients only. Presumably, we also want to do the ping/pong to ensure liveness, and the network crawl to try to fill the buckets.

So that would break down into:
- [ ] A new set of Kademlia buckets for tracking
- [ ] Use ping to ensure peer liveness
- [ ] Respond to the overlay "find nodes" using peers from the new buckets
- [ ] Crawl the peers in the overlay network to fill buckets
- [ ] When "found content" has an empty payload, use the new buckets to fill it (ie~ in `find_nodes_close_to_content()`)

This is a fairly large issue, bigger than one PR presumably. So if whoever works on this wants to open separate issues for each task I'd 👍🏻 . Otherwise, I'm happy to split this into subtasks after someone submits the first PR (maybe just the first bullet above?). I think that splitting, and identifying next tasks, will be easier once there's a bit more structure.

**Comment by carver** [comment]
@SamWilsn want to take this on, or at least the first steps of it?

**Comment by carver** [comment]
@jacobkaufmann seems to already be looking at how to extract and make some of the Kademlia logic easily available, so maybe look for an initial PR from him first, @SamWilsn .

**Comment by jacobkaufmann** [comment]
It looks like Piper's proposal for an alternative, non-XOR distance metric would likely rule out the option to use the `sigp/discv5` library directly for the state network bucket table. The XOR distance metric method is baked in to a lot of core logic, and I'm not sure supporting a custom distance metric is something that makes sense for `sigp/discv5`.

And even if we did not require support for a non-XOR distance metric, the Kademlia structures are kept private in the `sigp/discv5` library.

For the `libp2p/rust-libp2p` library, which is what the `sigp/discv5` Kademlia implementation is based on, the distance situation appears the same, but the Kademlia structures are made public.

I'm not sure we can get away from extracting and modifying the Kademlia logic, at least for the state network. And if we need to do so for the state network, then my thought is that we should use the same implementation for both the state and history networks. In other words, if we need to extract our own implementation for at least one overlay network, we should re-use that implementation across all overlay networks.

**Comment by jacobkaufmann** [comment]
Opened a [PR](https://github.com/sigp/discv5/pull/82) on the `sigp/discv5` repository to make the Kademlia items public.
